// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/jjs/demerits/shared/client.proto

package com.jjs.demerits.shared;

public final class DemeritsProto {
  private DemeritsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NoteOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string text = 1;
    boolean hasText();
    String getText();
    
    // optional string from = 2;
    boolean hasFrom();
    String getFrom();
    
    // optional string to = 3;
    boolean hasTo();
    String getTo();
    
    // optional int64 date = 4;
    boolean hasDate();
    long getDate();
    
    // optional bool demerit = 5;
    boolean hasDemerit();
    boolean getDemerit();
  }
  public static final class Note extends
      com.google.protobuf.GeneratedMessage
      implements NoteOrBuilder {
    // Use Note.newBuilder() to construct.
    private Note(Builder builder) {
      super(builder);
    }
    private Note(boolean noInit) {}
    
    private static final Note defaultInstance;
    public static Note getDefaultInstance() {
      return defaultInstance;
    }
    
    public Note getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_Note_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_Note_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string to = 3;
    public static final int TO_FIELD_NUMBER = 3;
    private java.lang.Object to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          to_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 date = 4;
    public static final int DATE_FIELD_NUMBER = 4;
    private long date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getDate() {
      return date_;
    }
    
    // optional bool demerit = 5;
    public static final int DEMERIT_FIELD_NUMBER = 5;
    private boolean demerit_;
    public boolean hasDemerit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getDemerit() {
      return demerit_;
    }
    
    private void initFields() {
      text_ = "";
      from_ = "";
      to_ = "";
      date_ = 0L;
      demerit_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, demerit_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getToBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, demerit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.Note parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jjs.demerits.shared.DemeritsProto.Note prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_Note_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_Note_fieldAccessorTable;
      }
      
      // Construct using com.jjs.demerits.shared.DemeritsProto.Note.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        demerit_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjs.demerits.shared.DemeritsProto.Note.getDescriptor();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.Note getDefaultInstanceForType() {
        return com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.Note build() {
        com.jjs.demerits.shared.DemeritsProto.Note result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.jjs.demerits.shared.DemeritsProto.Note buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.jjs.demerits.shared.DemeritsProto.Note result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.jjs.demerits.shared.DemeritsProto.Note buildPartial() {
        com.jjs.demerits.shared.DemeritsProto.Note result = new com.jjs.demerits.shared.DemeritsProto.Note(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.demerit_ = demerit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjs.demerits.shared.DemeritsProto.Note) {
          return mergeFrom((com.jjs.demerits.shared.DemeritsProto.Note)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jjs.demerits.shared.DemeritsProto.Note other) {
        if (other == com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance()) return this;
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasDemerit()) {
          setDemerit(other.getDemerit());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              from_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              to_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              date_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              demerit_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string text = 1;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
      }
      
      // optional string from = 2;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
      }
      
      // optional string to = 3;
      private java.lang.Object to_ = "";
      public boolean hasTo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      void setTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        to_ = value;
        onChanged();
      }
      
      // optional int64 date = 4;
      private long date_ ;
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getDate() {
        return date_;
      }
      public Builder setDate(long value) {
        bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = 0L;
        onChanged();
        return this;
      }
      
      // optional bool demerit = 5;
      private boolean demerit_ ;
      public boolean hasDemerit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getDemerit() {
        return demerit_;
      }
      public Builder setDemerit(boolean value) {
        bitField0_ |= 0x00000010;
        demerit_ = value;
        onChanged();
        return this;
      }
      public Builder clearDemerit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        demerit_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Note)
    }
    
    static {
      defaultInstance = new Note(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Note)
  }
  
  public interface NoteListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string email = 1;
    boolean hasEmail();
    String getEmail();
    
    // repeated .Note fromUser = 2;
    java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> 
        getFromUserList();
    com.jjs.demerits.shared.DemeritsProto.Note getFromUser(int index);
    int getFromUserCount();
    java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
        getFromUserOrBuilderList();
    com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getFromUserOrBuilder(
        int index);
    
    // repeated .Note toUser = 3;
    java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> 
        getToUserList();
    com.jjs.demerits.shared.DemeritsProto.Note getToUser(int index);
    int getToUserCount();
    java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
        getToUserOrBuilderList();
    com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getToUserOrBuilder(
        int index);
  }
  public static final class NoteList extends
      com.google.protobuf.GeneratedMessage
      implements NoteListOrBuilder {
    // Use NoteList.newBuilder() to construct.
    private NoteList(Builder builder) {
      super(builder);
    }
    private NoteList(boolean noInit) {}
    
    private static final NoteList defaultInstance;
    public static NoteList getDefaultInstance() {
      return defaultInstance;
    }
    
    public NoteList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_NoteList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_NoteList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .Note fromUser = 2;
    public static final int FROMUSER_FIELD_NUMBER = 2;
    private java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> fromUser_;
    public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> getFromUserList() {
      return fromUser_;
    }
    public java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
        getFromUserOrBuilderList() {
      return fromUser_;
    }
    public int getFromUserCount() {
      return fromUser_.size();
    }
    public com.jjs.demerits.shared.DemeritsProto.Note getFromUser(int index) {
      return fromUser_.get(index);
    }
    public com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getFromUserOrBuilder(
        int index) {
      return fromUser_.get(index);
    }
    
    // repeated .Note toUser = 3;
    public static final int TOUSER_FIELD_NUMBER = 3;
    private java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> toUser_;
    public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> getToUserList() {
      return toUser_;
    }
    public java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
        getToUserOrBuilderList() {
      return toUser_;
    }
    public int getToUserCount() {
      return toUser_.size();
    }
    public com.jjs.demerits.shared.DemeritsProto.Note getToUser(int index) {
      return toUser_.get(index);
    }
    public com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getToUserOrBuilder(
        int index) {
      return toUser_.get(index);
    }
    
    private void initFields() {
      email_ = "";
      fromUser_ = java.util.Collections.emptyList();
      toUser_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmailBytes());
      }
      for (int i = 0; i < fromUser_.size(); i++) {
        output.writeMessage(2, fromUser_.get(i));
      }
      for (int i = 0; i < toUser_.size(); i++) {
        output.writeMessage(3, toUser_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmailBytes());
      }
      for (int i = 0; i < fromUser_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, fromUser_.get(i));
      }
      for (int i = 0; i < toUser_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, toUser_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.NoteList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jjs.demerits.shared.DemeritsProto.NoteList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jjs.demerits.shared.DemeritsProto.NoteListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_NoteList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_NoteList_fieldAccessorTable;
      }
      
      // Construct using com.jjs.demerits.shared.DemeritsProto.NoteList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFromUserFieldBuilder();
          getToUserFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (fromUserBuilder_ == null) {
          fromUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          fromUserBuilder_.clear();
        }
        if (toUserBuilder_ == null) {
          toUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          toUserBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjs.demerits.shared.DemeritsProto.NoteList.getDescriptor();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.NoteList getDefaultInstanceForType() {
        return com.jjs.demerits.shared.DemeritsProto.NoteList.getDefaultInstance();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.NoteList build() {
        com.jjs.demerits.shared.DemeritsProto.NoteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.jjs.demerits.shared.DemeritsProto.NoteList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.jjs.demerits.shared.DemeritsProto.NoteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.jjs.demerits.shared.DemeritsProto.NoteList buildPartial() {
        com.jjs.demerits.shared.DemeritsProto.NoteList result = new com.jjs.demerits.shared.DemeritsProto.NoteList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        if (fromUserBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            fromUser_ = java.util.Collections.unmodifiableList(fromUser_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.fromUser_ = fromUser_;
        } else {
          result.fromUser_ = fromUserBuilder_.build();
        }
        if (toUserBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            toUser_ = java.util.Collections.unmodifiableList(toUser_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.toUser_ = toUser_;
        } else {
          result.toUser_ = toUserBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjs.demerits.shared.DemeritsProto.NoteList) {
          return mergeFrom((com.jjs.demerits.shared.DemeritsProto.NoteList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jjs.demerits.shared.DemeritsProto.NoteList other) {
        if (other == com.jjs.demerits.shared.DemeritsProto.NoteList.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (fromUserBuilder_ == null) {
          if (!other.fromUser_.isEmpty()) {
            if (fromUser_.isEmpty()) {
              fromUser_ = other.fromUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFromUserIsMutable();
              fromUser_.addAll(other.fromUser_);
            }
            onChanged();
          }
        } else {
          if (!other.fromUser_.isEmpty()) {
            if (fromUserBuilder_.isEmpty()) {
              fromUserBuilder_.dispose();
              fromUserBuilder_ = null;
              fromUser_ = other.fromUser_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fromUserBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFromUserFieldBuilder() : null;
            } else {
              fromUserBuilder_.addAllMessages(other.fromUser_);
            }
          }
        }
        if (toUserBuilder_ == null) {
          if (!other.toUser_.isEmpty()) {
            if (toUser_.isEmpty()) {
              toUser_ = other.toUser_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureToUserIsMutable();
              toUser_.addAll(other.toUser_);
            }
            onChanged();
          }
        } else {
          if (!other.toUser_.isEmpty()) {
            if (toUserBuilder_.isEmpty()) {
              toUserBuilder_.dispose();
              toUserBuilder_ = null;
              toUser_ = other.toUser_;
              bitField0_ = (bitField0_ & ~0x00000004);
              toUserBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getToUserFieldBuilder() : null;
            } else {
              toUserBuilder_.addAllMessages(other.toUser_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              email_ = input.readBytes();
              break;
            }
            case 18: {
              com.jjs.demerits.shared.DemeritsProto.Note.Builder subBuilder = com.jjs.demerits.shared.DemeritsProto.Note.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFromUser(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.jjs.demerits.shared.DemeritsProto.Note.Builder subBuilder = com.jjs.demerits.shared.DemeritsProto.Note.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addToUser(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string email = 1;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
      }
      
      // repeated .Note fromUser = 2;
      private java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> fromUser_ =
        java.util.Collections.emptyList();
      private void ensureFromUserIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          fromUser_ = new java.util.ArrayList<com.jjs.demerits.shared.DemeritsProto.Note>(fromUser_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> fromUserBuilder_;
      
      public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> getFromUserList() {
        if (fromUserBuilder_ == null) {
          return java.util.Collections.unmodifiableList(fromUser_);
        } else {
          return fromUserBuilder_.getMessageList();
        }
      }
      public int getFromUserCount() {
        if (fromUserBuilder_ == null) {
          return fromUser_.size();
        } else {
          return fromUserBuilder_.getCount();
        }
      }
      public com.jjs.demerits.shared.DemeritsProto.Note getFromUser(int index) {
        if (fromUserBuilder_ == null) {
          return fromUser_.get(index);
        } else {
          return fromUserBuilder_.getMessage(index);
        }
      }
      public Builder setFromUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFromUserIsMutable();
          fromUser_.set(index, value);
          onChanged();
        } else {
          fromUserBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFromUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          ensureFromUserIsMutable();
          fromUser_.set(index, builderForValue.build());
          onChanged();
        } else {
          fromUserBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFromUser(com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFromUserIsMutable();
          fromUser_.add(value);
          onChanged();
        } else {
          fromUserBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFromUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFromUserIsMutable();
          fromUser_.add(index, value);
          onChanged();
        } else {
          fromUserBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFromUser(
          com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          ensureFromUserIsMutable();
          fromUser_.add(builderForValue.build());
          onChanged();
        } else {
          fromUserBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFromUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          ensureFromUserIsMutable();
          fromUser_.add(index, builderForValue.build());
          onChanged();
        } else {
          fromUserBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFromUser(
          java.lang.Iterable<? extends com.jjs.demerits.shared.DemeritsProto.Note> values) {
        if (fromUserBuilder_ == null) {
          ensureFromUserIsMutable();
          super.addAll(values, fromUser_);
          onChanged();
        } else {
          fromUserBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFromUser() {
        if (fromUserBuilder_ == null) {
          fromUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fromUserBuilder_.clear();
        }
        return this;
      }
      public Builder removeFromUser(int index) {
        if (fromUserBuilder_ == null) {
          ensureFromUserIsMutable();
          fromUser_.remove(index);
          onChanged();
        } else {
          fromUserBuilder_.remove(index);
        }
        return this;
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder getFromUserBuilder(
          int index) {
        return getFromUserFieldBuilder().getBuilder(index);
      }
      public com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getFromUserOrBuilder(
          int index) {
        if (fromUserBuilder_ == null) {
          return fromUser_.get(index);  } else {
          return fromUserBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
           getFromUserOrBuilderList() {
        if (fromUserBuilder_ != null) {
          return fromUserBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(fromUser_);
        }
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder addFromUserBuilder() {
        return getFromUserFieldBuilder().addBuilder(
            com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance());
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder addFromUserBuilder(
          int index) {
        return getFromUserFieldBuilder().addBuilder(
            index, com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance());
      }
      public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note.Builder> 
           getFromUserBuilderList() {
        return getFromUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
          getFromUserFieldBuilder() {
        if (fromUserBuilder_ == null) {
          fromUserBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder>(
                  fromUser_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          fromUser_ = null;
        }
        return fromUserBuilder_;
      }
      
      // repeated .Note toUser = 3;
      private java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> toUser_ =
        java.util.Collections.emptyList();
      private void ensureToUserIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          toUser_ = new java.util.ArrayList<com.jjs.demerits.shared.DemeritsProto.Note>(toUser_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> toUserBuilder_;
      
      public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note> getToUserList() {
        if (toUserBuilder_ == null) {
          return java.util.Collections.unmodifiableList(toUser_);
        } else {
          return toUserBuilder_.getMessageList();
        }
      }
      public int getToUserCount() {
        if (toUserBuilder_ == null) {
          return toUser_.size();
        } else {
          return toUserBuilder_.getCount();
        }
      }
      public com.jjs.demerits.shared.DemeritsProto.Note getToUser(int index) {
        if (toUserBuilder_ == null) {
          return toUser_.get(index);
        } else {
          return toUserBuilder_.getMessage(index);
        }
      }
      public Builder setToUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.set(index, value);
          onChanged();
        } else {
          toUserBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setToUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.set(index, builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addToUser(com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.add(value);
          onChanged();
        } else {
          toUserBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addToUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureToUserIsMutable();
          toUser_.add(index, value);
          onChanged();
        } else {
          toUserBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addToUser(
          com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.add(builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addToUser(
          int index, com.jjs.demerits.shared.DemeritsProto.Note.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.add(index, builderForValue.build());
          onChanged();
        } else {
          toUserBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllToUser(
          java.lang.Iterable<? extends com.jjs.demerits.shared.DemeritsProto.Note> values) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          super.addAll(values, toUser_);
          onChanged();
        } else {
          toUserBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearToUser() {
        if (toUserBuilder_ == null) {
          toUser_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          toUserBuilder_.clear();
        }
        return this;
      }
      public Builder removeToUser(int index) {
        if (toUserBuilder_ == null) {
          ensureToUserIsMutable();
          toUser_.remove(index);
          onChanged();
        } else {
          toUserBuilder_.remove(index);
        }
        return this;
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder getToUserBuilder(
          int index) {
        return getToUserFieldBuilder().getBuilder(index);
      }
      public com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder getToUserOrBuilder(
          int index) {
        if (toUserBuilder_ == null) {
          return toUser_.get(index);  } else {
          return toUserBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
           getToUserOrBuilderList() {
        if (toUserBuilder_ != null) {
          return toUserBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(toUser_);
        }
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder addToUserBuilder() {
        return getToUserFieldBuilder().addBuilder(
            com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance());
      }
      public com.jjs.demerits.shared.DemeritsProto.Note.Builder addToUserBuilder(
          int index) {
        return getToUserFieldBuilder().addBuilder(
            index, com.jjs.demerits.shared.DemeritsProto.Note.getDefaultInstance());
      }
      public java.util.List<com.jjs.demerits.shared.DemeritsProto.Note.Builder> 
           getToUserBuilderList() {
        return getToUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder> 
          getToUserFieldBuilder() {
        if (toUserBuilder_ == null) {
          toUserBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.jjs.demerits.shared.DemeritsProto.Note, com.jjs.demerits.shared.DemeritsProto.Note.Builder, com.jjs.demerits.shared.DemeritsProto.NoteOrBuilder>(
                  toUser_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          toUser_ = null;
        }
        return toUserBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:NoteList)
    }
    
    static {
      defaultInstance = new NoteList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NoteList)
  }
  
  public interface UpdateGcmIdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string email = 1;
    boolean hasEmail();
    String getEmail();
    
    // optional string gcmId = 2;
    boolean hasGcmId();
    String getGcmId();
    
    // optional bool register = 3;
    boolean hasRegister();
    boolean getRegister();
  }
  public static final class UpdateGcmId extends
      com.google.protobuf.GeneratedMessage
      implements UpdateGcmIdOrBuilder {
    // Use UpdateGcmId.newBuilder() to construct.
    private UpdateGcmId(Builder builder) {
      super(builder);
    }
    private UpdateGcmId(boolean noInit) {}
    
    private static final UpdateGcmId defaultInstance;
    public static UpdateGcmId getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpdateGcmId getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_UpdateGcmId_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjs.demerits.shared.DemeritsProto.internal_static_UpdateGcmId_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string gcmId = 2;
    public static final int GCMID_FIELD_NUMBER = 2;
    private java.lang.Object gcmId_;
    public boolean hasGcmId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getGcmId() {
      java.lang.Object ref = gcmId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          gcmId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getGcmIdBytes() {
      java.lang.Object ref = gcmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        gcmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool register = 3;
    public static final int REGISTER_FIELD_NUMBER = 3;
    private boolean register_;
    public boolean hasRegister() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getRegister() {
      return register_;
    }
    
    private void initFields() {
      email_ = "";
      gcmId_ = "";
      register_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGcmIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, register_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGcmIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, register_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.jjs.demerits.shared.DemeritsProto.UpdateGcmId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jjs.demerits.shared.DemeritsProto.UpdateGcmId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.jjs.demerits.shared.DemeritsProto.UpdateGcmIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_UpdateGcmId_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjs.demerits.shared.DemeritsProto.internal_static_UpdateGcmId_fieldAccessorTable;
      }
      
      // Construct using com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        gcmId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        register_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.getDescriptor();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.UpdateGcmId getDefaultInstanceForType() {
        return com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.getDefaultInstance();
      }
      
      public com.jjs.demerits.shared.DemeritsProto.UpdateGcmId build() {
        com.jjs.demerits.shared.DemeritsProto.UpdateGcmId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.jjs.demerits.shared.DemeritsProto.UpdateGcmId buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.jjs.demerits.shared.DemeritsProto.UpdateGcmId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.jjs.demerits.shared.DemeritsProto.UpdateGcmId buildPartial() {
        com.jjs.demerits.shared.DemeritsProto.UpdateGcmId result = new com.jjs.demerits.shared.DemeritsProto.UpdateGcmId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.gcmId_ = gcmId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.register_ = register_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjs.demerits.shared.DemeritsProto.UpdateGcmId) {
          return mergeFrom((com.jjs.demerits.shared.DemeritsProto.UpdateGcmId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.jjs.demerits.shared.DemeritsProto.UpdateGcmId other) {
        if (other == com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasGcmId()) {
          setGcmId(other.getGcmId());
        }
        if (other.hasRegister()) {
          setRegister(other.getRegister());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              email_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              gcmId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              register_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string email = 1;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
      }
      
      // optional string gcmId = 2;
      private java.lang.Object gcmId_ = "";
      public boolean hasGcmId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getGcmId() {
        java.lang.Object ref = gcmId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          gcmId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setGcmId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        gcmId_ = value;
        onChanged();
        return this;
      }
      public Builder clearGcmId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gcmId_ = getDefaultInstance().getGcmId();
        onChanged();
        return this;
      }
      void setGcmId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        gcmId_ = value;
        onChanged();
      }
      
      // optional bool register = 3;
      private boolean register_ ;
      public boolean hasRegister() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getRegister() {
        return register_;
      }
      public Builder setRegister(boolean value) {
        bitField0_ |= 0x00000004;
        register_ = value;
        onChanged();
        return this;
      }
      public Builder clearRegister() {
        bitField0_ = (bitField0_ & ~0x00000004);
        register_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:UpdateGcmId)
    }
    
    static {
      defaultInstance = new UpdateGcmId(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:UpdateGcmId)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Note_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Note_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NoteList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NoteList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGcmId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UpdateGcmId_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$com/jjs/demerits/shared/client.proto\"M" +
      "\n\004Note\022\014\n\004text\030\001 \001(\t\022\014\n\004from\030\002 \001(\t\022\n\n\002to" +
      "\030\003 \001(\t\022\014\n\004date\030\004 \001(\003\022\017\n\007demerit\030\005 \001(\010\"I\n" +
      "\010NoteList\022\r\n\005email\030\001 \001(\t\022\027\n\010fromUser\030\002 \003" +
      "(\0132\005.Note\022\025\n\006toUser\030\003 \003(\0132\005.Note\"=\n\013Upda" +
      "teGcmId\022\r\n\005email\030\001 \001(\t\022\r\n\005gcmId\030\002 \001(\t\022\020\n" +
      "\010register\030\003 \001(\010B(\n\027com.jjs.demerits.shar" +
      "edB\rDemeritsProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Note_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Note_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Note_descriptor,
              new java.lang.String[] { "Text", "From", "To", "Date", "Demerit", },
              com.jjs.demerits.shared.DemeritsProto.Note.class,
              com.jjs.demerits.shared.DemeritsProto.Note.Builder.class);
          internal_static_NoteList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NoteList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NoteList_descriptor,
              new java.lang.String[] { "Email", "FromUser", "ToUser", },
              com.jjs.demerits.shared.DemeritsProto.NoteList.class,
              com.jjs.demerits.shared.DemeritsProto.NoteList.Builder.class);
          internal_static_UpdateGcmId_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_UpdateGcmId_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UpdateGcmId_descriptor,
              new java.lang.String[] { "Email", "GcmId", "Register", },
              com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.class,
              com.jjs.demerits.shared.DemeritsProto.UpdateGcmId.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
